// const currencyFlag = [
//   { currency_code: 'USD', flag: '🇺🇸' },
//   { currency_code: 'CAD', flag: '🇨🇦' },
//   { currency_code: 'EUR', flag: '🇪🇺' },
//   { currency_code: 'AED', flag: '🇦🇪' },
//   { currency_code: 'AFN', flag: '🇦🇫' },
//   { currency_code: 'ALL', flag: '🇦🇱' },
//   { currency_code: 'AMD', flag: '🇦🇲' },
//   { currency_code: 'ARS', flag: '🇦🇷' },
//   { currency_code: 'AUD', flag: '🇦🇺' },
//   { currency_code: 'AZN', flag: '🇦🇿' },
//   { currency_code: 'BAM', flag: '🇧🇦' },
//   { currency_code: 'BDT', flag: '🇧🇩' },
//   { currency_code: 'BGN', flag: '🇧🇬' },
//   { currency_code: 'BHD', flag: '🇧🇭' },
//   { currency_code: 'BIF', flag: '🇧🇮' },
//   { currency_code: 'BND', flag: '🇧🇳' },
//   { currency_code: 'BOB', flag: '🇧🇴' },
//   { currency_code: 'BRL', flag: '🇧🇷' },
//   { currency_code: 'BWP', flag: '🇧🇼' },
//   { currency_code: 'BYR', flag: '🇧🇾' },
//   { currency_code: 'BZD', flag: '🇧🇿' },
//   { currency_code: 'CDF', flag: '🇨🇩' },
//   { currency_code: 'CHF', flag: '🇨🇭' },
//   { currency_code: 'CLP', flag: '🇨🇱' },
//   { currency_code: 'CNY', flag: '🇨🇳' },
//   { currency_code: 'COP', flag: '🇨🇴' },
//   { currency_code: 'CRC', flag: '🇨🇷' },
//   { currency_code: 'CVE', flag: '🇨🇻' },
//   { currency_code: 'CZK', flag: '🇨🇿' },
//   { currency_code: 'DJF', flag: '🇩🇯' },
//   { currency_code: 'DKK', flag: '🇩🇰' },
//   { currency_code: 'DOP', flag: '🇩🇴' },
//   { currency_code: 'DZD', flag: '🇩🇿' },
//   { currency_code: 'EEK', flag: '🇪🇪' },
//   { currency_code: 'EGP', flag: '🇪🇬' },
//   { currency_code: 'ERN', flag: '🇪🇷' },
//   { currency_code: 'ETB', flag: '🇪🇹' },
//   { currency_code: 'GBP', flag: '🇬🇧' },
//   { currency_code: 'GEL', flag: '🇬🇪' },
//   { currency_code: 'GHS', flag: '🇬🇭' },
//   { currency_code: 'GNF', flag: '🇬🇳' },
//   { currency_code: 'GTQ', flag: '🇬🇹' },
//   { currency_code: 'HKD', flag: '🇭🇰' },
//   { currency_code: 'HNL', flag: '🇭🇳' },
//   { currency_code: 'HRK', flag: '🇭🇷' },
//   { currency_code: 'HUF', flag: '🇭🇺' },
//   { currency_code: 'IDR', flag: '🇮🇩' },
//   { currency_code: 'ILS', flag: '🇮🇱' },
//   { currency_code: 'INR', flag: '🇮🇳' },
//   { currency_code: 'IQD', flag: '🇮🇶' },
//   { currency_code: 'IRR', flag: '🇮🇷' },
//   { currency_code: 'ISK', flag: '🇮🇸' },
//   { currency_code: 'JMD', flag: '🇯🇲' },
//   { currency_code: 'JOD', flag: '🇯🇴' },
//   { currency_code: 'JPY', flag: '🇯🇵' },
//   { currency_code: 'KES', flag: '🇰🇪' },
//   { currency_code: 'KGS', flag: '🇰🇬' },
//   { currency_code: 'KHR', flag: '🇰🇭' },
//   { currency_code: 'KMF', flag: '🇰🇲' },
//   { currency_code: 'KPW', flag: '🇰🇵' },
//   { currency_code: 'KRW', flag: '🇰🇷' },
//   { currency_code: 'KWD', flag: '🇰🇼' },
//   { currency_code: 'KYD', flag: '🇰🇾' },
//   { currency_code: 'KZT', flag: '🇰🇿' },
//   { currency_code: 'LAK', flag: '🇱🇦' },
//   { currency_code: 'LBP', flag: '🇱🇧' },
//   { currency_code: 'LKR', flag: '🇱🇰' },
//   { currency_code: 'LRD', flag: '🇱🇷' },
//   { currency_code: 'LSL', flag: '🇱🇸' },
//   { currency_code: 'LTL', flag: '🇱🇹' },
//   { currency_code: 'LVL', flag: '🇱🇻' },
//   { currency_code: 'LYD', flag: '🇱🇾' },
//   { currency_code: 'MAD', flag: '🇲🇦' },
//   { currency_code: 'MDL', flag: '🇲🇩' },
//   { currency_code: 'MGA', flag: '🇲🇬' },
//   { currency_code: 'MKD', flag: '🇲🇰' },
//   { currency_code: 'MMK', flag: '🇲🇲' },
//   { currency_code: 'MNT', flag: '🇲🇳' },
//   { currency_code: 'MOP', flag: '🇲🇴' },
//   { currency_code: 'MUR', flag: '🇲🇺' },
//   { currency_code: 'MVR', flag: '🇲🇻' },
//   { currency_code: 'MWK', flag: '🇲🇼' },
//   { currency_code: 'MXN', flag: '🇲🇽' },
//   { currency_code: 'MYR', flag: '🇲🇾' },
//   { currency_code: 'MZN', flag: '🇲🇿' },
//   { currency_code: 'NAD', flag: '🇳🇦' },
//   { currency_code: 'NGN', flag: '🇳🇬' },
//   { currency_code: 'NIO', flag: '🇳🇮' },
//   { currency_code: 'NOK', flag: '🇳🇴' },
//   { currency_code: 'NPR', flag: '🇳🇵' },
//   { currency_code: 'NZD', flag: '🇳🇿' },
//   { currency_code: 'OMR', flag: '🇴🇲' },
//   { currency_code: 'PAB', flag: '🇵🇦' },
//   { currency_code: 'PEN', flag: '🇵🇪' },
//   { currency_code: 'PGK', flag: '🇵🇬' },
//   { currency_code: 'PHP', flag: '🇵🇭' },
//   { currency_code: 'PKR', flag: '🇵🇰' },
//   { currency_code: 'PLN', flag: '🇵🇱' },
//   { currency_code: 'PYG', flag: '🇵🇾' },
//   { currency_code: 'QAR', flag: '🇶🇦' },
//   { currency_code: 'RON', flag: '🇷🇴' },
//   { currency_code: 'RSD', flag: '🇷🇸' },
//   { currency_code: 'RUB', flag: '🇷🇺' },
//   { currency_code: 'RWF', flag: '🇷🇼' },
//   { currency_code: 'SAR', flag: '🇸🇦' },
//   { currency_code: 'SBD', flag: '🇸🇧' },
//   { currency_code: 'SCR', flag: '🇸🇨' },
//   { currency_code: 'SDG', flag: '🇸🇩' },
//   { currency_code: 'SEK', flag: '🇸🇪' },
//   { currency_code: 'SGD', flag: '🇸🇬' },
//   { currency_code: 'SHP', flag: '🇸🇭' },
//   { currency_code: 'SLL', flag: '🇸🇱' },
//   { currency_code: 'SOS', flag: '🇸🇴' },
//   { currency_code: 'SRD', flag: '🇸🇷' },
//   { currency_code: 'SSP', flag: '🇸🇸' },
//   { currency_code: 'STD', flag: '🇸🇹' },
//   { currency_code: 'SVC', flag: '🇸🇻' },
//   { currency_code: 'SYP', flag: '🇸🇾' },
//   { currency_code: 'SZL', flag: '🇸🇿' },
//   { currency_code: 'THB', flag: '🇹🇭' },
//   { currency_code: 'TJS', flag: '🇹🇯' },
//   { currency_code: 'TMT', flag: '🇹🇲' },
//   { currency_code: 'TND', flag: '🇹🇳' },
//   { currency_code: 'TOP', flag: '🇹🇴' },
//   { currency_code: 'TRY', flag: '🇹🇷' },
//   { currency_code: 'TTD', flag: '🇹🇹' },
//   { currency_code: 'TWD', flag: '🇹🇼' },
//   { currency_code: 'TZS', flag: '🇹🇿' },
//   { currency_code: 'UAH', flag: '🇺🇦' },
//   { currency_code: 'UGX', flag: '🇺🇬' },
//   { currency_code: 'UYU', flag: '🇺🇾' },
//   { currency_code: 'UZS', flag: '🇺🇿' },
//   { currency_code: 'VEF', flag: '🇻🇪' },
//   { currency_code: 'VND', flag: '🇻🇳' },
//   { currency_code: 'VUV', flag: '🇻🇺' },
//   { currency_code: 'WST', flag: '🇼🇸' },
//   { currency_code: 'XAF', flag: '🇨🇫' },
//   { currency_code: 'XCD', flag: '🇧🇲' },
//   { currency_code: 'XOF', flag: '🇧🇫' },
//   { currency_code: 'XPF', flag: '🇵🇫' },
//   { currency_code: 'YER', flag: '🇾🇪' },
//   { currency_code: 'ZAR', flag: '🇿🇦' },
//   { currency_code: 'ZMK', flag: '🇿🇲' },
// ];

// // export const currencyOptions = (currencyList) => {
// //   return currencyList.map((x) => {
// //     return {
// //       value: x.currency_code,
// //       label:
// //         (currencyFlag.find((currency) => currency.currency_code === x.currency_code)?.flag ||
// //           '💵') +
// //         ' ' +
// //         x.currency_symbol +
// //         ' (' +
// //         x.currency_name +
// //         ')',
// //     };
// //   });
// // };

// export const currencyOptions = () => {
//   return currencyFlag.map((x) => {
//     return {
//       value: x.currency_code,
//       label: x.flag + ' ' + x.currency_code,
//     };
//   });
// };
const currencyFlag = [
  { currency_code: 'USD', flag: '🇺🇸' },
  { currency_code: 'CAD', flag: '🇨🇦' },
  { currency_code: 'EUR', flag: '🇪🇺' },
  { currency_code: 'AED', flag: '🇦🇪' },
  { currency_code: 'AFN', flag: '🇦🇫' },
  { currency_code: 'ALL', flag: '🇦🇱' },
  { currency_code: 'AMD', flag: '🇦🇲' },
  { currency_code: 'ARS', flag: '🇦🇷' },
  { currency_code: 'AUD', flag: '🇦🇺' },
  { currency_code: 'AZN', flag: '🇦🇿' },
  { currency_code: 'BAM', flag: '🇧🇦' },
  { currency_code: 'BDT', flag: '🇧🇩' },
  { currency_code: 'BGN', flag: '🇧🇬' },
  { currency_code: 'BHD', flag: '🇧🇭' },
  { currency_code: 'BIF', flag: '🇧🇮' },
  { currency_code: 'BND', flag: '🇧🇳' },
  { currency_code: 'BOB', flag: '🇧🇴' },
  { currency_code: 'BRL', flag: '🇧🇷' },
  { currency_code: 'BWP', flag: '🇧🇼' },
  { currency_code: 'BYR', flag: '🇧🇾' },
  { currency_code: 'BZD', flag: '🇧🇿' },
  { currency_code: 'CDF', flag: '🇨🇩' },
  { currency_code: 'CHF', flag: '🇨🇭' },
  { currency_code: 'CLP', flag: '🇨🇱' },
  { currency_code: 'CNY', flag: '🇨🇳' },
  { currency_code: 'COP', flag: '🇨🇴' },
  { currency_code: 'CRC', flag: '🇨🇷' },
  { currency_code: 'CVE', flag: '🇨🇻' },
  { currency_code: 'CZK', flag: '🇨🇿' },
  { currency_code: 'DJF', flag: '🇩🇯' },
  { currency_code: 'DKK', flag: '🇩🇰' },
  { currency_code: 'DOP', flag: '🇩🇴' },
  { currency_code: 'DZD', flag: '🇩🇿' },
  { currency_code: 'EEK', flag: '🇪🇪' },
  { currency_code: 'EGP', flag: '🇪🇬' },
  { currency_code: 'ERN', flag: '🇪🇷' },
  { currency_code: 'ETB', flag: '🇪🇹' },
  { currency_code: 'GBP', flag: '🇬🇧' },
  { currency_code: 'GEL', flag: '🇬🇪' },
  { currency_code: 'GHS', flag: '🇬🇭' },
  { currency_code: 'GNF', flag: '🇬🇳' },
  { currency_code: 'GTQ', flag: '🇬🇹' },
  { currency_code: 'HKD', flag: '🇭🇰' },
  { currency_code: 'HNL', flag: '🇭🇳' },
  { currency_code: 'HRK', flag: '🇭🇷' },
  { currency_code: 'HUF', flag: '🇭🇺' },
  { currency_code: 'IDR', flag: '🇮🇩' },
  { currency_code: 'ILS', flag: '🇮🇱' },
  { currency_code: 'INR', flag: '🇮🇳' },
  { currency_code: 'IQD', flag: '🇮🇶' },
  { currency_code: 'IRR', flag: '🇮🇷' },
  { currency_code: 'ISK', flag: '🇮🇸' },
  { currency_code: 'JMD', flag: '🇯🇲' },
  { currency_code: 'JOD', flag: '🇯🇴' },
  { currency_code: 'JPY', flag: '🇯🇵' },
  { currency_code: 'KES', flag: '🇰🇪' },
  { currency_code: 'KGS', flag: '🇰🇬' },
  { currency_code: 'KHR', flag: '🇰🇭' },
  { currency_code: 'KMF', flag: '🇰🇲' },
  { currency_code: 'KPW', flag: '🇰🇵' },
  { currency_code: 'KRW', flag: '🇰🇷' },
  { currency_code: 'KWD', flag: '🇰🇼' },
  { currency_code: 'KYD', flag: '🇰🇾' },
  { currency_code: 'KZT', flag: '🇰🇿' },
  { currency_code: 'LAK', flag: '🇱🇦' },
  { currency_code: 'LBP', flag: '🇱🇧' },
  { currency_code: 'LKR', flag: '🇱🇰' },
  { currency_code: 'LRD', flag: '🇱🇷' },
  { currency_code: 'LSL', flag: '🇱🇸' },
  { currency_code: 'LTL', flag: '🇱🇹' },
  { currency_code: 'LVL', flag: '🇱🇻' },
  { currency_code: 'LYD', flag: '🇱🇾' },
  { currency_code: 'MAD', flag: '🇲🇦' },
  { currency_code: 'MDL', flag: '🇲🇩' },
  { currency_code: 'MGA', flag: '🇲🇬' },
  { currency_code: 'MKD', flag: '🇲🇰' },
  { currency_code: 'MMK', flag: '🇲🇲' },
  { currency_code: 'MNT', flag: '🇲🇳' },
  { currency_code: 'MOP', flag: '🇲🇴' },
  { currency_code: 'MUR', flag: '🇲🇺' },
  { currency_code: 'MVR', flag: '🇲🇻' },
  { currency_code: 'MWK', flag: '🇲🇼' },
  { currency_code: 'MXN', flag: '🇲🇽' },
  { currency_code: 'MYR', flag: '🇲🇾' },
  { currency_code: 'MZN', flag: '🇲🇿' },
  { currency_code: 'NAD', flag: '🇳🇦' },
  { currency_code: 'NGN', flag: '🇳🇬' },
  { currency_code: 'NIO', flag: '🇳🇮' },
  { currency_code: 'NOK', flag: '🇳🇴' },
  { currency_code: 'NPR', flag: '🇳🇵' },
  { currency_code: 'NZD', flag: '🇳🇿' },
  { currency_code: 'OMR', flag: '🇴🇲' },
  { currency_code: 'PAB', flag: '🇵🇦' },
  { currency_code: 'PEN', flag: '🇵🇪' },
  { currency_code: 'PGK', flag: '🇵🇬' },
  { currency_code: 'PHP', flag: '🇵🇭' },
  { currency_code: 'PKR', flag: '🇵🇰' },
  { currency_code: 'PLN', flag: '🇵🇱' },
  { currency_code: 'PYG', flag: '🇵🇾' },
  { currency_code: 'QAR', flag: '🇶🇦' },
  { currency_code: 'RON', flag: '🇷🇴' },
  { currency_code: 'RSD', flag: '🇷🇸' },
  { currency_code: 'RUB', flag: '🇷🇺' },
  { currency_code: 'RWF', flag: '🇷🇼' },
  { currency_code: 'SAR', flag: '🇸🇦' },
  { currency_code: 'SBD', flag: '🇸🇧' },
  { currency_code: 'SCR', flag: '🇸🇨' },
  { currency_code: 'SDG', flag: '🇸🇩' },
  { currency_code: 'SEK', flag: '🇸🇪' },
  { currency_code: 'SGD', flag: '🇸🇬' },
  { currency_code: 'SHP', flag: '🇸🇭' },
  { currency_code: 'SLL', flag: '🇸🇱' },
  { currency_code: 'SOS', flag: '🇸🇴' },
  { currency_code: 'SRD', flag: '🇸🇷' },
  { currency_code: 'SSP', flag: '🇸🇸' },
  { currency_code: 'STD', flag: '🇸🇹' },
  { currency_code: 'SVC', flag: '🇸🇻' },
  { currency_code: 'SYP', flag: '🇸🇾' },
  { currency_code: 'SZL', flag: '🇸🇿' },
  { currency_code: 'THB', flag: '🇹🇭' },
  { currency_code: 'TJS', flag: '🇹🇯' },
  { currency_code: 'TMT', flag: '🇹🇲' },
  { currency_code: 'TND', flag: '🇹🇳' },
  { currency_code: 'TOP', flag: '🇹🇴' },
  { currency_code: 'TRY', flag: '🇹🇷' },
  { currency_code: 'TTD', flag: '🇹🇹' },
  { currency_code: 'TWD', flag: '🇹🇼' },
  { currency_code: 'TZS', flag: '🇹🇿' },
  { currency_code: 'UAH', flag: '🇺🇦' },
  { currency_code: 'UGX', flag: '🇺🇬' },
  { currency_code: 'UYU', flag: '🇺🇾' },
  { currency_code: 'UZS', flag: '🇺🇿' },
  { currency_code: 'VEF', flag: '🇻🇪' },
  { currency_code: 'VND', flag: '🇻🇳' },
  { currency_code: 'VUV', flag: '🇻🇺' },
  { currency_code: 'WST', flag: '🇼🇸' },
  { currency_code: 'XAF', flag: '🇨🇫' },
  { currency_code: 'XCD', flag: '🇧🇲' },
  { currency_code: 'XOF', flag: '🇧🇫' },
  { currency_code: 'XPF', flag: '🇵🇫' },
  { currency_code: 'YER', flag: '🇾🇪' },
  { currency_code: 'ZAR', flag: '🇿🇦' },
  { currency_code: 'ZMK', flag: '🇿🇲' },
];
const languageFlag = [
  { language_name: 'English', flag: '🇺🇸' },
  { language_name: 'French', flag: '🇫🇷' },
  { language_name: 'German', flag: '🇩🇪' },
  { language_name: 'Spanish', flag: '🇪🇸' },
  { language_name: 'Italian', flag: '🇮🇹' },
  { language_name: 'Portuguese', flag: '🇵🇹' },
  { language_name: 'Dutch', flag: '🇳🇱' },
  { language_name: 'Russian', flag: '🇷🇺' },
  { language_name: 'Chinese', flag: '🇨🇳' },
  { language_name: 'Japanese', flag: '🇯🇵' },
  { language_name: 'Korean', flag: '🇰🇷' },
  { language_name: 'Arabic', flag: '🇸🇦' },
  { language_name: 'Turkish', flag: '🇹🇷' },
  { language_name: 'Hindi', flag: '🇮🇳' },
  { language_name: 'Bengali', flag: '🇧🇩' },
  { language_name: 'Urdu', flag: '🇵🇰' },
  { language_name: 'Persian', flag: '🇮🇷' },
  { language_name: 'Thai', flag: '🇹🇭' },
  { language_name: 'Vietnamese', flag: '🇻🇳' },
  { language_name: 'Indonesian', flag: '🇮🇩' },
  { language_name: 'Malay', flag: '🇲🇾' },
  { language_name: 'Filipino', flag: '🇵🇭' },
  { language_name: 'Swedish', flag: '🇸🇪' },
  { language_name: 'Danish', flag: '🇩🇰' },
  { language_name: 'Finnish', flag: '🇫🇮' },
  { language_name: 'Norwegian', flag: '🇳🇴' },
  { language_name: 'Greek', flag: '🇬🇷' },
  { language_name: 'Czech', flag: '🇨🇿' },
  { language_name: 'Polish', flag: '🇵🇱' },
  { language_name: 'Hungarian', flag: '🇭🇺' },
  { language_name: 'Romanian', flag: '🇷🇴' },
  { language_name: 'Bulgarian', flag: '🇧🇬' },
  { language_name: 'Serbian', flag: '🇷🇸' },
  { language_name: 'Croatian', flag: '🇭🇷' },
  { language_name: 'Slovak', flag: '🇸🇰' },
  { language_name: 'Slovenian', flag: '🇸🇮' },
  { language_name: 'Estonian', flag: '🇪🇪' },
  { language_name: 'Latvian', flag: '🇱🇻' },
  { language_name: 'Lithuanian', flag: '🇱🇹' },
  { language_name: 'Maltese', flag: '🇲🇹' },
  { language_name: 'Icelandic', flag: '🇮🇸' },
  { language_name: 'Kazakh', flag: '🇰🇿' },
  { language_name: 'Georgian', flag: '🇬🇪' },
  { language_name: 'Albanian', flag: '🇦🇱' },
  { language_name: 'Macedonian', flag: '🇲🇰' },
  { language_name: 'Ukrainian', flag: '🇺🇦' },
  { language_name: 'Belarusian', flag: '🇧🇾' },
  { language_name: 'Afrikaans', flag: '🇿🇦' },
  { language_name: 'Zulu', flag: '🇿🇦' },
  { language_name: 'Xhosa', flag: '🇿🇦' },
  { language_name: 'Swahili', flag: '🇰🇪' },
  { language_name: 'Yoruba', flag: '🇳🇬' },
  { language_name: 'Hausa', flag: '🇳🇬' },
  { language_name: 'Igbo', flag: '🇳🇬' },
  { language_name: 'Somali', flag: '🇸🇴' },
  { language_name: 'Amharic', flag: '🇪🇹' },
  { language_name: 'Oromo', flag: '🇪🇹' },
  { language_name: 'Tigrinya', flag: '🇪🇷' },
  { language_name: 'Hebrew', flag: '🇮🇱' },
  { language_name: 'Armenian', flag: '🇦🇲' },
  { language_name: 'Uzbek', flag: '🇺🇿' },
  { language_name: 'Pashto', flag: '🇦🇫' },
  { language_name: 'Kurdish', flag: '🇮🇶' },
  { language_name: 'Turkmen', flag: '🇹🇲' },
  { language_name: 'Kyrgyz', flag: '🇰🇬' },
  { language_name: 'Tajik', flag: '🇹🇯' },
  { language_name: 'Tswana', flag: '🇧🇼' },
  { language_name: 'Sotho', flag: '🇱🇸' },
  { language_name: 'Tsonga', flag: '🇿🇦' },
  { language_name: 'Northern Sotho', flag: '🇿🇦' },
  { language_name: 'Venda', flag: '🇿🇦' },
  { language_name: 'Ndebele', flag: '🇿🇦' },
  { language_name: 'Filipino (Tagalog)', flag: '🇵🇭' },
  { language_name: 'Malagasy', flag: '🇲🇬' },
  { language_name: 'Sesotho', flag: '🇱🇸' },
  { language_name: 'Chichewa', flag: '🇲🇼' },
  { language_name: 'Kinyarwanda', flag: '🇷🇼' },
  { language_name: 'Wolof', flag: '🇸🇳' },
  { language_name: 'Twi', flag: '🇬🇭' },
  { language_name: 'Shona', flag: '🇿🇼' },
  { language_name: 'Kanuri', flag: '🇳🇬' },
  { language_name: 'Swati', flag: '🇸🇿' },
  { language_name: 'Gujarati', flag: '🇮🇳' },
  { language_name: 'Telugu', flag: '🇮🇳' },
  { language_name: 'Tamil', flag: '🇮🇳' },
  { language_name: 'Punjabi', flag: '🇮🇳' },
  { language_name: 'Kannada', flag: '🇮🇳' },
  { language_name: 'Malayalam', flag: '🇮🇳' },
  { language_name: 'Marathi', flag: '🇮🇳' },
  { language_name: 'Assamese', flag: '🇮🇳' },
  { language_name: 'Odia (Oriya)', flag: '🇮🇳' },
  { language_name: 'Sindhi', flag: '🇵🇰' },
  { language_name: 'Nepali', flag: '🇳🇵' },
  { language_name: 'Kirundi', flag: '🇧🇮' },
  { language_name: 'Kurdish (Kurmanji)', flag: '🇮🇶' },
  { language_name: 'Tetum', flag: '🇹🇱' },
  { language_name: 'Chewa', flag: '🇲🇼' },
  { language_name: 'Twi (Akan)', flag: '🇬🇭' },
  { language_name: 'Ewe', flag: '🇹🇬'},
  { language_name: 'Fon', flag: '🇧🇯'}
]

export const currencyList = [
  { currency_code: 'USD', currency_symbol: '$', currency_name: 'US Dollar' },
  { currency_code: 'CAD', currency_symbol: 'CA$', currency_name: 'Canadian Dollar' },
  { currency_code: 'EUR', currency_symbol: '€', currency_name: 'Euro' },
  { currency_code: 'AED', currency_symbol: 'د.إ', currency_name: 'United Arab Emirates Dirham' },
  { currency_code: 'AFN', currency_symbol: 'Af', currency_name: 'Afghan Afghani' },
  { currency_code: 'ALL', currency_symbol: 'L', currency_name: 'Albanian Lek' },
  { currency_code: 'AMD', currency_symbol: '֏', currency_name: 'Armenian Dram' },
  { currency_code: 'ARS', currency_symbol: '$', currency_name: 'Argentine Peso' },
  { currency_code: 'AUD', currency_symbol: 'A$', currency_name: 'Australian Dollar' },
  { currency_code: 'AZN', currency_symbol: '₼', currency_name: 'Azerbaijani Manat' },
  { currency_code: 'BAM', currency_symbol: 'KM', currency_name: 'Bosnia-Herzegovina Convertible Mark' },
  { currency_code: 'BDT', currency_symbol: '৳', currency_name: 'Bangladeshi Taka' },
  { currency_code: 'BGN', currency_symbol: 'лв', currency_name: 'Bulgarian Lev' },
  { currency_code: 'BHD', currency_symbol: '.د.ب', currency_name: 'Bahraini Dinar' },
  { currency_code: 'BIF', currency_symbol: 'FBu', currency_name: 'Burundian Franc' },
  { currency_code: 'BND', currency_symbol: 'B$', currency_name: 'Brunei Dollar' },
  { currency_code: 'BOB', currency_symbol: 'Bs.', currency_name: 'Bolivian Boliviano' },
  { currency_code: 'BRL', currency_symbol: 'R$', currency_name: 'Brazilian Real' },
  { currency_code: 'BWP', currency_symbol: 'P', currency_name: 'Botswana Pula' },
  { currency_code: 'BYR', currency_symbol: 'Br', currency_name: 'Belarusian Ruble' },
  { currency_code: 'BZD', currency_symbol: 'BZ$', currency_name: 'Belize Dollar' },
  { currency_code: 'CDF', currency_symbol: 'FC', currency_name: 'Congolese Franc' },
  { currency_code: 'CHF', currency_symbol: 'CHF', currency_name: 'Swiss Franc' },
  { currency_code: 'CLP', currency_symbol: '$', currency_name: 'Chilean Peso' },
  { currency_code: 'CNY', currency_symbol: '¥', currency_name: 'Chinese Yuan' },
  { currency_code: 'COP', currency_symbol: '$', currency_name: 'Colombian Peso' },
  { currency_code: 'CRC', currency_symbol: '₡', currency_name: 'Costa Rican Colón' },
  { currency_code: 'CVE', currency_symbol: '$', currency_name: 'Cape Verdean Escudo' },
  { currency_code: 'CZK', currency_symbol: 'Kč', currency_name: 'Czech Koruna' },
  { currency_code: 'DJF', currency_symbol: 'Fdj', currency_name: 'Djiboutian Franc' },
  { currency_code: 'DKK', currency_symbol: 'kr', currency_name: 'Danish Krone' },
  { currency_code: 'DOP', currency_symbol: 'RD$', currency_name: 'Dominican Peso' },
  { currency_code: 'DZD', currency_symbol: 'د.ج', currency_name: 'Algerian Dinar' },
  { currency_code: 'EEK', currency_symbol: 'kr', currency_name: 'Estonian Kroon' },
  { currency_code: 'EGP', currency_symbol: '£', currency_name: 'Egyptian Pound' },
  { currency_code: 'ERN', currency_symbol: 'Nfk', currency_name: 'Eritrean Nakfa' },
  { currency_code: 'ETB', currency_symbol: 'Br', currency_name: 'Ethiopian Birr' },
  { currency_code: 'GBP', currency_symbol: '£', currency_name: 'British Pound' },
  { currency_code: 'GEL', currency_symbol: '₾', currency_name: 'Georgian Lari' },
  { currency_code: 'GHS', currency_symbol: 'GH₵', currency_name: 'Ghanaian Cedi' },
  { currency_code: 'GNF', currency_symbol: 'FG', currency_name: 'Guinean Franc' },
  { currency_code: 'GTQ', currency_symbol: 'Q', currency_name: 'Guatemalan Quetzal' },
  { currency_code: 'HKD', currency_symbol: 'HK$', currency_name: 'Hong Kong Dollar' },
  { currency_code: 'HNL', currency_symbol: 'L', currency_name: 'Honduran Lempira' },
  { currency_code: 'HRK', currency_symbol: 'kn', currency_name: 'Croatian Kuna' },
  { currency_code: 'HUF', currency_symbol: 'Ft', currency_name: 'Hungarian Forint' },
  { currency_code: 'IDR', currency_symbol: 'Rp', currency_name: 'Indonesian Rupiah' },
  { currency_code: 'ILS', currency_symbol: '₪', currency_name: 'Israeli New Shekel' },
  { currency_code: 'INR', currency_symbol: '₹', currency_name: 'Indian Rupee' },
  { currency_code: 'IQD', currency_symbol: 'ع.د', currency_name: 'Iraqi Dinar' },
  { currency_code: 'IRR', currency_symbol: '﷼', currency_name: 'Iranian Rial' },
  { currency_code: 'ISK', currency_symbol: 'kr', currency_name: 'Icelandic Króna' },
  { currency_code: 'JMD', currency_symbol: 'J$', currency_name: 'Jamaican Dollar' },
  { currency_code: 'JOD', currency_symbol: 'د.ا', currency_name: 'Jordanian Dinar' },
  { currency_code: 'JPY', currency_symbol: '¥', currency_name: 'Japanese Yen' },
  { currency_code: 'KES', currency_symbol: 'KSh', currency_name: 'Kenyan Shilling' },
  { currency_code: 'KGS', currency_symbol: 'лв', currency_name: 'Kyrgyzstani Som' },
  { currency_code: 'KHR', currency_symbol: '៛', currency_name: 'Cambodian Riel' },
  { currency_code: 'KMF', currency_symbol: 'CF', currency_name: 'Comorian Franc' },
  { currency_code: 'KPW', currency_symbol: '₩', currency_name: 'North Korean Won' },
  { currency_code: 'KRW', currency_symbol: '₩', currency_name: 'South Korean Won' },
  { currency_code: 'KWD', currency_symbol: 'د.ك', currency_name: 'Kuwaiti Dinar' },
  { currency_code: 'KYD', currency_symbol: 'CI$', currency_name: 'Cayman Islands Dollar' },
  { currency_code: 'KZT', currency_symbol: '₸', currency_name: 'Kazakhstani Tenge' },
  { currency_code: 'LAK', currency_symbol: '₭', currency_name: 'Lao Kip' },
  { currency_code: 'LBP', currency_symbol: 'ل.ل', currency_name: 'Lebanese Pound' },
  { currency_code: 'LKR', currency_symbol: 'Rs', currency_name: 'Sri Lankan Rupee' },
  { currency_code: 'LRD', currency_symbol: 'L$', currency_name: 'Liberian Dollar' },
  { currency_code: 'LSL', currency_symbol: 'L', currency_name: 'Lesotho Loti' },
  { currency_code: 'LTL', currency_symbol: 'Lt', currency_name: 'Lithuanian Litas' },
  { currency_code: 'LVL', currency_symbol: 'Ls', currency_name: 'Latvian Lats' },
  { currency_code: 'LYD', currency_symbol: 'ل.د', currency_name: 'Libyan Dinar' },
  { currency_code: 'MAD', currency_symbol: 'د.م.', currency_name: 'Moroccan Dirham' },
  { currency_code: 'MDL', currency_symbol: 'L', currency_name: 'Moldovan Leu' },
  { currency_code: 'MGA', currency_symbol: 'Ar', currency_name: 'Malagasy Ariary' },
  { currency_code: 'MKD', currency_symbol: 'ден', currency_name: 'Macedonian Denar' },
  { currency_code: 'MMK', currency_symbol: 'K', currency_name: 'Myanmar Kyat' },
  { currency_code: 'MNT', currency_symbol: '₮', currency_name: 'Mongolian Tögrög' },
  { currency_code: 'MOP', currency_symbol: 'P', currency_name: 'Macanese Pataca' },
  { currency_code: 'MUR', currency_symbol: '₨', currency_name: 'Mauritian Rupee' },
  { currency_code: 'MVR', currency_symbol: 'Rf', currency_name: 'Maldivian Rufiyaa' },
  { currency_code: 'MWK', currency_symbol: 'MK', currency_name: 'Malawian Kwacha' },
  { currency_code: 'MXN', currency_symbol: 'Mex$', currency_name: 'Mexican Peso' },
  { currency_code: 'MYR', currency_symbol: 'RM', currency_name: 'Malaysian Ringgit' },
  { currency_code: 'MZN', currency_symbol: 'MT', currency_name: 'Mozambican Metical' },
  { currency_code: 'NAD', currency_symbol: 'N$', currency_name: 'Namibian Dollar' },
  { currency_code: 'NGN', currency_symbol: '₦', currency_name: 'Nigerian Naira' },
  { currency_code: 'NIO', currency_symbol: 'C$', currency_name: 'Nicaraguan Córdoba' },
  { currency_code: 'NOK', currency_symbol: 'kr', currency_name: 'Norwegian Krone' },
  { currency_code: 'NPR', currency_symbol: '₨', currency_name: 'Nepalese Rupee' },
  { currency_code: 'NZD', currency_symbol: 'NZ$', currency_name: 'New Zealand Dollar' },
  { currency_code: 'OMR', currency_symbol: 'ر.ع.', currency_name: 'Omani Rial' },
  { currency_code: 'PAB', currency_symbol: 'B/.', currency_name: 'Panamanian Balboa' },
  { currency_code: 'PEN', currency_symbol: 'S/.', currency_name: 'Peruvian Sol' },
  { currency_code: 'PGK', currency_symbol: 'K', currency_name: 'Papua New Guinean Kina' },
  { currency_code: 'PHP', currency_symbol: '₱', currency_name: 'Philippine Peso' },
  { currency_code: 'PKR', currency_symbol: '₨', currency_name: 'Pakistani Rupee' },
  { currency_code: 'PLN', currency_symbol: 'zł', currency_name: 'Polish Złoty' },
  { currency_code: 'PYG', currency_symbol: '₲', currency_name: 'Paraguayan Guaraní' },
  { currency_code: 'QAR', currency_symbol: 'ر.ق', currency_name: 'Qatari Riyal' },
  { currency_code: 'RON', currency_symbol: 'lei', currency_name: 'Romanian Leu' },
  { currency_code: 'RSD', currency_symbol: 'din', currency_name: 'Serbian Dinar' },
  { currency_code: 'RUB', currency_symbol: '₽', currency_name: 'Russian Ruble' },
  { currency_code: 'RWF', currency_symbol: 'FRw', currency_name: 'Rwandan Franc' },
  { currency_code: 'SAR', currency_symbol: 'ر.س', currency_name: 'Saudi Riyal' },
  { currency_code: 'SBD', currency_symbol: 'SI$', currency_name: 'Solomon Islands Dollar' },
  { currency_code: 'SCR', currency_symbol: '₨', currency_name: 'Seychellois Rupee' },
  { currency_code: 'SDG', currency_symbol: '£', currency_name: 'Sudanese Pound' },
  { currency_code: 'SEK', currency_symbol: 'kr', currency_name: 'Swedish Krona' },
  { currency_code: 'SGD', currency_symbol: 'S$', currency_name: 'Singapore Dollar' },
  { currency_code: 'SHP', currency_symbol: '£', currency_name: 'Saint Helena Pound' },
  { currency_code: 'SLL', currency_symbol: 'Le', currency_name: 'Sierra Leonean Leone' },
  { currency_code: 'SOS', currency_symbol: 'Sh', currency_name: 'Somali Shilling' },
  { currency_code: 'SRD', currency_symbol: '$', currency_name: 'Surinamese Dollar' },
  { currency_code: 'SSP', currency_symbol: '£', currency_name: 'South Sudanese Pound' },
  { currency_code: 'STD', currency_symbol: 'Db', currency_name: 'São Tomé and Príncipe Dobra' },
  { currency_code: 'SVC', currency_symbol: '$', currency_name: 'Salvadoran Colón' },
  { currency_code: 'SYP', currency_symbol: '£', currency_name: 'Syrian Pound' },
  { currency_code: 'SZL', currency_symbol: 'E', currency_name: 'Swazi Lilangeni' },
  { currency_code: 'THB', currency_symbol: '฿', currency_name: 'Thai Baht' },
  { currency_code: 'TJS', currency_symbol: 'ЅМ', currency_name: 'Tajikistani Somoni' },
  { currency_code: 'TMT', currency_symbol: 'm', currency_name: 'Turkmenistani Manat' },
  { currency_code: 'TND', currency_symbol: 'د.ت', currency_name: 'Tunisian Dinar' },
  { currency_code: 'TOP', currency_symbol: 'T$', currency_name: 'Tongan Paʻanga' },
  { currency_code: 'TRY', currency_symbol: '₺', currency_name: 'Turkish Lira' },
  { currency_code: 'TTD', currency_symbol: 'TT$', currency_name: 'Trinidad and Tobago Dollar' },
  { currency_code: 'TWD', currency_symbol: 'NT$', currency_name: 'New Taiwan Dollar' },
  { currency_code: 'TZS', currency_symbol: 'Sh', currency_name: 'Tanzanian Shilling' },
  { currency_code: 'UAH', currency_symbol: '₴', currency_name: 'Ukrainian Hryvnia' },
  { currency_code: 'UGX', currency_symbol: 'USh', currency_name: 'Ugandan Shilling' },
  { currency_code: 'UYU', currency_symbol: '$U', currency_name: 'Uruguayan Peso' },
  { currency_code: 'UZS', currency_symbol: 'лв', currency_name: 'Uzbekistani Som' },
  { currency_code: 'VEF', currency_symbol: 'Bs F', currency_name: 'Venezuelan Bolívar' },
  { currency_code: 'VND', currency_symbol: '₫', currency_name: 'Vietnamese Đồng' },
  { currency_code: 'VUV', currency_symbol: 'VT', currency_name: 'Vanuatu Vatu' },
  { currency_code: 'WST', currency_symbol: 'T', currency_name: 'Samoan Tala' },
  { currency_code: 'XAF', currency_symbol: 'FCFA', currency_name: 'Central African CFA Franc' },
  { currency_code: 'XCD', currency_symbol: 'EC$', currency_name: 'East Caribbean Dollar' },
  { currency_code: 'XOF', currency_symbol: 'CFA', currency_name: 'West African CFA Franc' },
  { currency_code: 'XPF', currency_symbol: '₣', currency_name: 'CFP Franc' },
  { currency_code: 'YER', currency_symbol: '﷼', currency_name: 'Yemeni Rial' },
  { currency_code: 'ZAR', currency_symbol: 'R', currency_name: 'South African Rand' },
  { currency_code: 'ZMK', currency_symbol: 'ZK', currency_name: 'Zambian Kwacha' },
  { currency_code: 'ZWL', currency_symbol: 'Z$', currency_name: 'Zimbabwean Dollar' }
];

export const currencyOptions = () => {
  return currencyFlag.map((x) => {
    return {
      value: x.currency_code,
      label: x.flag + ' ' + x.currency_code,
    };
  });
};


export const languageOptions = () => {
  return languageFlag.map((x) => {
    return {
      value: x.language_name,
      label: x.flag + ' ' + x.language_name,
    };
  });
};

// export const currencyOptions = (currencyList) => {
//   return currencyList.map((x) => {
//     const flag = currencyFlag.find((currency) => currency.currency_code === x.currency_code)?.flag || '💵';
//     return {
//       value: x.currency_code,
//       label: `${flag} ${x.currency_symbol} (${x.currency_name})`,
//     };
//   });
// };

// Usage:
// const options = currencyOptions(currencyList);
// console.log(options);
